### ISSUE TITLE
Should Strings as Argument Default Values be Highlighted?

### ISSUE THREAD

**Issue by liuderchi** [atom/language-coffee-script#111]
In CoffeeScript

![screenshot from 2017-01-17 10 50 09](https://cloud.githubusercontent.com/assets/4994705/22006038/e0ff83fc-dca2-11e6-858b-ead7046d2756.png)
```coffee
class Person
  greet: (msg='hello') ->
    console.log msg
```

`'hello'` is **not highlighted**, while in js:
```javascript
// JavaScript
function greet(msg='hello') {
  console.log(msg);
}
var greet = (msg='hello') =>
  console.log(msg);
```

Versions:
`language-coffee-script` v0.48.2
`Atom` v1.14.0-beta1

BTW I am not sure whether this issue is included in #103

**Comment by 50Wliu** [comment]
Yes, this will be fixed by #103.
![image](https://cloud.githubusercontent.com/assets/2766036/22008039/76cfb66c-dc45-11e6-8b85-0130fbf74a99.png)
