### ISSUE TITLE
Incorrect highlighting of regexp followed by string with slash

### ISSUE THREAD

**Issue by foucdeg** [atom/language-coffee-script#123]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On a line with a regexp followed by a string which includes a slash, that slash is incorrectly interpreted as the end of the regexp. Therefore, anything after the ending quotation mark for the string is highlighted as being inside a string. This is incorrect as the code compiles correctly to Javascript.

### Steps to Reproduce
Write the following line in a file with Coffee syntax highlighting:
`[/test/, '/'] # this is inside a string ' # this is not`

**Expected behavior:** [What you expect to happen]

Correct syntax highlighting displayed by [js2.coffee](http://js2.coffee):
![image](https://cloud.githubusercontent.com/assets/12948989/25441902/d0bf85c4-2aa3-11e7-9bfd-9ea5131b19c5.png)

**Actual behavior:** [What actually happens]
![image](https://cloud.githubusercontent.com/assets/12948989/25441919/df299bd6-2aa3-11e7-924d-9f544c4b0144.png)

### Versions
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.7.3

language-coffee-script 0.48.5

**Comment by 50Wliu** [comment]
This has been fixed and should be included in Atom 1.17.0.
