### ISSUE TITLE
Slash in string makes everything matching as a regex

### ISSUE THREAD

**Issue by bhauteki** [atom/language-coffee-script#124]
The syntax colouring goes wrong with next example

```
string.replace(/test/, "test/")
// now everything is coloured as a regular expression
```

The second argument is a normal string, and the slash should not be treated different.

### Versions

Atom: v1.16.0
Language-coffee-script : v0.48.5

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.17.0, currently in beta.
