### ISSUE TITLE
Regular expressions with escaped backslashes only partially highlighted

### ISSUE THREAD

**Issue by Alhadis** [atom/language-coffee-script#127]
Relates to #119, which appears to have only been partly successful in fixing regex highlighting:

~~~coffee
signature: /^\.TH[ \t]+(?:\S+)|^'\\" [tre]+(?=\s|$)|^\.so[ \t]+man(\w+)\/.+\.\1(?=\s|$)|^\.(EQ|PS|cstart)\n|^'{3}\t\\" /]
~~~

Might be better to attach a screenshot to show how badly this can affect output:

<img src="https://cloud.githubusercontent.com/assets/2346707/26142250/1a900130-3b23-11e7-91c6-17348d25ee89.png" width="700" alt="Figure 1" />

Note the quote being matched at the end of the expression.

**Comment by Alhadis** [comment]
Could everybody take a moment to appreciate the fact I slapped that attachment together so fast, I didn't even notice I'd accidentally hidden the text layer before exporting from Photoshop:

<img src="https://cloud.githubusercontent.com/assets/2346707/26142491/1bd341e6-3b24-11e7-8481-e33dcca5bb11.png" width="700" alt="lol" />

Bear in mind I managed to run this through TinyPic and upload the attachment before noticing what was missing.

(Shortcut-accelerated workflows tend to be helpful only when one's paying attention to what the hell they're doing...)

/cc @simurai to laugh at me

**Comment by 50Wliu** [comment]
Here's a simpler example.
```coffee
uriRegex = /config\/([a-z]+)\/?([a-zA-Z0-9_-]+)?/i
#                           ^^ UH OH
```
