### ISSUE TITLE
String interpolation with ternary expression breaks highlighting

### ISSUE THREAD

**Issue by mjbvz** [atom/language-coffee-script#158]
From https://github.com/Microsoft/vscode/issues/36422

### Bug

For the code:

```coffe
"a b c 1 2 3 #{if true is true then "uid" else (alert 'Uid') + " as uid"} a b c 1 2 3"
```

The interpolated string expression breaks highlighting for the rest of the document:

<img width="657" alt="screen shot 2017-10-17 at 11 35 16 am" src="https://user-images.githubusercontent.com/12821956/31682585-68ca8878-b32f-11e7-83de-aa2d8ea804bc.png">

Note that the `a b c 1 2 3` after the expression is not highlighted as a string but instead as an expression

### Versions

0.49

**Comment by 50Wliu** [comment]
![coffee-ternary](https://user-images.githubusercontent.com/2766036/31684245-586772ca-b37f-11e7-85bf-6d9ed63f537a.png)
Cannot reproduce on 8873cbc.
