### ISSUE TITLE
Built-in CoffeeScript extension doesn't highlight ES2015 module syntax

### ISSUE THREAD

**Issue by aeschli** [atom/language-coffee-script#167]
_From @jdemilledt on June 4, 2018 14:9_

- VSCode Version: 1.23.1
- OS Version: Arch Linux - no real version

Steps to Reproduce:

1. Use ES2015 module syntax in CoffeeScript

Does this issue occur when all extensions are disabled?: This is an issue with a built-in extension

Expected: When using the [ES2015 module syntax in CoffeeScript](https://coffeescript.org/#modules), imports and exports are highlighted with colors  
Actual behavior: All text for ES2015 imports/exports is white

_Copied from original issue: Microsoft/vscode#51086_

**Comment by Arcanemagus** [comment]
@jdemilledt Could you be more specific about what "colors" you were expecting?

The example given from coffeescript.org appears to be being highlighted better than it is on coffeescript.org at least:
![image](https://user-images.githubusercontent.com/427137/41051144-22a47632-696a-11e8-91fc-541f7e1ac235.png)

**Comment by jdemilledt** [comment]
![image](https://user-images.githubusercontent.com/29146969/41053297-234a8864-6989-11e8-908a-cf616818adcd.png)

**Comment by Arcanemagus** [comment]
@aeschli I'm guessing they are talking about how `import`, `from` and the like aren't being highlighted. Atom is marking those as `keyword.control.coffee`, does VSC have a way of debugging it to check if they are getting parsed and just not themed over there?

For reference, this code:

```coffee
import m from "mitrhil"
import { Toolbar, Drawer, List, ListTile, IconButton, ToolbarTitle } from "poluthene-mithril"
import { MenuIcon } from "./assets/icons.coffee"
import { routeIs } from "./util.coffee"
```

is rendered by Atom as:
![image](https://user-images.githubusercontent.com/427137/41053693-22505492-6971-11e8-8126-226b1a8bfce5.png)

**Comment by jdemilledt** [comment]
I've managed to find the developer tools. I'll look into it and see

**Comment by jdemilledt** [comment]
Looks like `mtk<number>` classes control text color. I'm seeing the import lines being classified as `mtk1`, which is the same class used for non-colored code

**Comment by jdemilledt** [comment]
![image](https://user-images.githubusercontent.com/29146969/41055865-626732ac-6990-11e8-817b-2326f07cbddd.png)
![image](https://user-images.githubusercontent.com/29146969/41055885-6e4840fc-6990-11e8-9d50-09f5ea8d3b18.png)
That's in JS

![image](https://user-images.githubusercontent.com/29146969/41055924-8e1a95d8-6990-11e8-997a-22fecd7072d1.png)
That's CoffeeScript

**Comment by aeschli** [comment]
That's how VSCode renders it
![image](https://user-images.githubusercontent.com/6461412/41059674-7d94a572-69cd-11e8-8e5d-6d6b4912e157.png)

Sorry, I moved the issue too quickly. Looks like all is fine on the grammar side but likely a problem of the theme. @jdemilledt Let's continue the discussion in Microsoft/vscode#51086
