### ISSUE TITLE
"Editor is not defined" Error

### ISSUE THREAD

**Issue by Guar1** [atom/language-coffee-script#169]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * The problem will NOT reproduce in in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    [X]* Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

the problem 👎  
"Failed to load C:\Users\**\.atom\init.coffee
editor is not defined"

pops up in red at startup.

Running a Dell XPS 13 box with Windows 10, using atom for python coding.

### Steps to Reproduce

1. [Open Atom]
2. [Error!]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
No error
**Actual behavior:** [What actually happens]
Error
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
This is an issue with your `init.coffee` file.

**Comment by Ridgeway22** [comment]
How  do I fix this error? new to JavaScript

**Comment by Arcanemagus** [comment]
For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
