### ISSUE TITLE
Color keyword operators as control keywords

### ISSUE THREAD

**Issue by OttoRobba** [atom/language-coffee-script#29]
I believe that keyword operators such as and|or|isnt should not be the same color as other operators (==|!=|+=) because, while they are still in the same category, they are often used in a different manner.

My proposal is having them receive the same coloring as control keywords.

On the left, the current one. On the right, the proposed change.
[Imgur](http://i.imgur.com/QCLQXGC.png)
![samplesyntax](https://cloud.githubusercontent.com/assets/597287/3686334/cd235488-1316-11e4-94b6-3e418927a948.png)

**Comment by limoragni** [comment]
+1

**Comment by MaximSokolov** [comment]
According [TextMate naming conventions](http://manual.macromates.com/en/language_grammars#naming_conventions) `and`, `or` are `keyword.operator`
What color would be `keyword.operator` depends on syntax theme you're using.

`wontfix` & close
Related issue is atom/atom#8430
