### ISSUE TITLE
Please add `class` to keyword list

### ISSUE THREAD

**Issue by zhanzhenzhen** [atom/language-coffee-script#33]
`class` is definitely a keyword.

**Comment by MaximSokolov** [comment]
According [TextMate naming conventions](http://manual.macromates.com/en/language_grammars#naming_conventions) `class` is `storage.type.class`
`wontfix` & close
Related issue is atom/atom#8430

**Comment by thomasjo** [comment]
I agree, `class` is **not** a keyword (by the definition used in the TextMate grammar docs).
