### ISSUE TITLE
/= causes regex highlighting with / in same line.

### ISSUE THREAD

**Issue by ilikebits** [atom/language-coffee-script#35]
This is an edge case, but the following valid CoffeeScript produces regex highlighting between the `/`'s in the conditional.
```coffeescript
a = 0
if (a /= 1) < (1 / 2)
  return 1 / 2
```

**Comment by kevinsawicki** [comment]
This issue appears to have been resolved. Please comment if you still see it happening in Atom 1.0.3+.

<img width="279" alt="screen shot 2015-07-31 at 9 06 04 am" src="https://cloud.githubusercontent.com/assets/671378/9011654/6d4e997e-3763-11e5-8008-5ea6d6421a86.png">
