### ISSUE TITLE
litcoffee code block not highlighted properly when after a list

### ISSUE THREAD

**Issue by PavelVanecek** [atom/language-coffee-script#43]
Including code block after a list breaks highlighting. See screenshot (source code on the left, markdown preview on the right):

![screen shot 2014-11-03 at 13 05 20](https://cloud.githubusercontent.com/assets/1100170/4882116/ba54a344-6351-11e4-8dfc-fdc25c6c88cb.png)

The example text:
```litcoffee
Some text in `.litcoffee` file with functions in it.

    a = ->
      m = 'indented function'
      return 'properly formatted ' + m

1. Example
2. List


    b = ->
      m = 'indendet function'
      return 'not highlighted ' + m

1. Another
2. List

With some text after it.

    c = ->
      m = 'indendet function'
      return 'properly highlighted ' + m
```
Save as `file.litcoffee` and open in atom.io. Function is not highlighted properly in editor, however markdown preview is fine.

**Comment by lexi-lambda** [comment]
+1, this is annoying, and I'd appreciate if it were fixed.

**Comment by redders6600** [comment]
Just noticed this too, thanks for pointing out that if you put text after the list it fixes the issue, handy workaround for now.
