### ISSUE TITLE
Colon in interpolated string breaks coloring

### ISSUE THREAD

**Issue by mzgajner** [atom/language-coffee-script#57]
CoffeeScript supports [string interpolation](http://coffeescript.org/#strings) in strings with double quotes. If I use it in a string that ends with a colon, coloring breaks - see screenshot below.
![screen shot 2015-06-01 at 10 09 48](https://cloud.githubusercontent.com/assets/1853648/7908567/5dd42744-0846-11e5-8adf-2f4bc7c8b48b.png)

```coffee
foo = [
    { value: 1 }
    { value: "#{var} :" }
    { value: "2" }
]
```

**Comment by 50Wliu** [comment]
Minimal reproduction case:
```coffee
{ a: "} :" }
```
The issue is that the snippet is incorrectly getting tokenized as `meta.variable.assignment.destructured.object.coffee` due to the bracket in the string.  Single quotes also exhibit this behavior, as does replacing all the braces with brackets.
