### ISSUE TITLE
Single quote character problematic in CoffeeScript

### ISSUE THREAD

**Issue by mdouglasbrett** [atom/language-coffee-script#61]
Hi :)

I initially posted this issue over at github/linguist#2529, and they referred me over here:

I came across this when I was looking through a README (https://github.com/zooniverse/Panoptes-Front-End):

```coffee
<ChangeListener target={auth}>{=>
  <PromiseRenderer promise={auth.checkCurrent()}>{(user) =>
    if user?
      <p>User is {user.display_name}</p>
    else
      <p>Nobody's signed in.</p>
  }</PromiseRenderer>
}</ChangeListener>

```
The single quote starts a string that doesn't end. I had a go at escaping it and I'm not sure that you can:

```coffee
<ChangeListener target={auth}>{=>
  <PromiseRenderer promise={auth.checkCurrent()}>{(user) =>
    if user?
      <p>User is {user.display_name}</p>
    else
      <p>Nobody\'s signed in.</p>
  }</PromiseRenderer>
}</ChangeListener>

```

Is this a bug, or am I missing something incredibly obvious?

All the best,

Mike

**Comment by 50Wliu** [comment]
This doesn't seem to be pure CoffeeScript to me, and coffeescript.org fails to transpile it back to Javascript, so I'm going to close this out.

Please comment here if I misunderstood something!
