### ISSUE TITLE
Bump version up to 0.43.0

### ISSUE THREAD

**Issue by adrianlee44** [atom/language-coffee-script#69]
@50Wliu, any chance you can bump this package to `0.43.0`?

**Comment by thedaniel** [comment]
I just did, and will update in atom as well.

**Comment by 50Wliu** [comment]
Sorry for the delay - apm isn't working on my Windows machine right now because of a bug in Git/apm, and I keep forgetting to boot up Ubuntu :cry:.

**Comment by adrianlee44** [comment]
Thanks @thedaniel and @50Wliu!
