### ISSUE TITLE
Error "unmatched parenthesis" with .litcoffee since atom update

### ISSUE THREAD

**Issue by davibe** [atom/language-coffee-script#71]
This is the error i get when the atom tries to syntax-hilight a .litcoffee file. This problem goes away if i disable language-coffee-script

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: end pattern with unmatched parenthesis

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:31

Error: end pattern with unmatched parenthesis
    at Error (native)
    at Scanner.module.exports.Scanner.createScanner (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:31:24)
    at Scanner.module.exports.Scanner.getScanner (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:37:31)
    at Scanner.module.exports.Scanner.findNextMatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:56:22)
    at Rule.module.exports.Rule.findNextMatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/rule.js:99:28)
    at Rule.module.exports.Rule.getNextTags (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/rule.js:141:21)
    at Grammar.module.exports.Grammar.tokenizeLine (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar.js:150:44)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:546:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:532:19)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:292:43)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:269:26
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47
```

### Commands

```
  7x -2:22.1.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -2:19.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:15.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -2:13.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:11.4.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -2:10.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  7x -2:08.6.0 blur (atom-text-editor.editor.mini.is-focused)
     -2:04.6.0 core:close (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -2:04.5.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -2:00.8.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
 33x -1:51.9.0 blur (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:18.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:40.7.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:37.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:37.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -0:26 blur (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "minimap",
      "minimap-autohide",
      "minimap-git-diff",
      "minimap-selection",
      "minimap-pigments",
      "last-cursor-position",
      "tidy-tabs",
      "color-tabs",
      "tab-switcher",
      "terminal-panel",
      "tree-view-git-status",
      "pane-split-moves-tab",
      "preview-plus",
      "source-preview",
      "vim-mode",
      "recent-files-fuzzy-finder"
    ],
    "themes": [
      "native-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "Monaco",
    "lineHeight": 1.2,
    "softWrap": true,
    "fontSize": 15,
    "preferredLineLength": 120
  }
}
```

### Installed Packages

```coffee
# User
antialiased, v0.1.0
api-blueprint-preview, v0.6.0
autocomplete-ctags, v0.3.2
autocomplete-modules, v1.3.1
autocomplete-python, v0.10.3
git-log, v0.4.1
language-api-blueprint, v1.0.2
language-cjsx, v0.3.0
language-docker, v1.1.3
language-groovy, v0.4.0
language-javascript-jsx, v0.3.7
markdown-preview-plus, v2.2.2
markdown-scroll-sync, v0.4.2
native-ui, v0.8.1
quick-highlight, v0.3.7
tabs-to-spaces, v0.11.1
vim-mode-plus, v0.2.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
If only it would say what line... :disappointed:.

**Comment by davibe** [comment]
does it happen to you ?

**Comment by B34rPG** [comment]
same situation here! does it fix?

**Comment by 50Wliu** [comment]
Looking into it.

**Comment by B34rPG** [comment]
@50Wliu Thanks for helping, and error msg won't show after merge your commit. However, my syntax color is a little bit different also...>_<

**Comment by B34rPG** [comment]
<img width="116" alt="2015-11-16 12 05 04" src="https://cloud.githubusercontent.com/assets/15855064/11174246/1730cfbe-8c5c-11e5-95bb-7fc41452ece7.png">

**Comment by 50Wliu** [comment]
Uh oh.  Can you share the contents of that file here?  If not, can you create an example that still doesn't work and then paste it here?  Thanks!

**Comment by B34rPG** [comment]
@50Wliu  Here is my litcoffee demo code.

[demo.txt](https://github.com/atom/language-coffee-script/files/36500/demo.txt)

**Comment by 50Wliu** [comment]
Thanks, that'll definitely help a lot.

**Comment by 50Wliu** [comment]
@B34rPG highlighting is working fine for me...

**Comment by B34rPG** [comment]
Syntax color is still wrong... what i have done is merging two files that you committed.

**Comment by B34rPG** [comment]
@50Wliu my mistake... and my highlighting is working fine too! thank you ;)

**Comment by 50Wliu** [comment]
@B34rPG Thanks for confirming!  I'll be publishing a new release once I get home this afternoon.

**Comment by fniessink** [comment]
Is there a work-around while we wait for the new release?

**Comment by 50Wliu** [comment]
Clone this repo, then execute `apm link` in the `language-coffee-script` folder.  Reload Atom, and you should be good!

**Comment by davibe** [comment]
you can just do `apm install language-coffee-script` it will override default one and work fine

**Comment by DomVinyard** [comment]
Hey sorry davibe, could you run through the steps for that command. I'm out of my depth here, I just need my syntax highlighted again so I can get some work done!

**Comment by davibe** [comment]
On MacOS
- Open the Terminal.app
- Type `api install language-coffee-script` in it
- Hit ENTER
- Wait for it to install the package
- Close terminal and restart Atom
- Profit

**Comment by DomVinyard** [comment]
`npm i atom-package-manager`
install Xcode command line tools when prompted
`apm install language-coffee-script`

still command not found

**Comment by 50Wliu** [comment]
@DomVinyard Open Atom.  Then, click the Atom menu and select "Install Command Line Tools" (or something like that).  After that finishes try `apm install language-coffee-script` again.

By the way, this should be in a future 1.2 patch release.

**Comment by DomVinyard** [comment]
Yay! 50Wliu you are amazing.

Atom menu > install shell commands
Terminal > `apm install language-coffee-script`
Returns a warning advising it's already installed and then outputs
`//Installing language-coffee-script to /Users/dom/.atom/packages ✓`

Atom > View menu > Reload

Syntax is once again highlighted. Thanks

**Comment by 50Wliu** [comment]
This fix is now in Atom 1.2.4 (and should be in 1.3.0-beta7 if/when it comes out).  For those who are on the stable channel, please `apm uninstall language-coffee-script` to set language-coffee-script back to Atom's bundled version.

**Comment by fniessink** [comment]
I don't see the fix in Atom 1.2.4 on Mac OS X 10.11.1 after installing the update, doing `apm uninstall language-coffee-script` and performing view -> reload.

**Comment by 50Wliu** [comment]
Hmm.  What version is language-coffee-script in the Settings View?  Perhaps it didn't make it in.

**Comment by fniessink** [comment]
I have 0.43.0 of language-coffee-script under core packages (and 0.45.0 under community packages, but that's the result of my manual `apm install language-coffee-script` I assume).

**Comment by 50Wliu** [comment]
Ok, then unfortunately 1.2.4 didn't catch the fix.  1.2.5/1.3.0-beta7 definitely should though.
