### ISSUE TITLE
Function calls aren't highlighted when first argument is @-prefixed

### ISSUE THREAD

**Issue by jonboiser** [atom/language-coffee-script#75]
atom@1.2.4, language-coffee-script@0.43.0, on OSX Yosmite
![image](https://cloud.githubusercontent.com/assets/10248067/11355720/cb201c12-921c-11e5-9ace-31ab005374a4.png)

I'd be happy to setup a PR with a spec for this, and try fixing it, but I'm not sure how to run the tests.

**Comment by 50Wliu** [comment]
There's two ways to run the tests:
1. Developer -> Run Package Specs inside of Atom (while the language-coffee-script folder is opened)
2. `atom --test spec` while in the language-coffee-script folder

The former has a UI, the latter is entirely CLI-based.

**Comment by jonboiser** [comment]
![screenshot 2015-11-24 15 33 29](https://cloud.githubusercontent.com/assets/10248067/11381281/c4aa9674-92c0-11e5-96d3-c82c8c0eca9a.png)

Looks okay with the fixes, but like I said IDK if there are any regressions. I can beef up the specs for functions and instance variables if you think they're needed.

**Comment by jonboiser** [comment]
I guess my issue wasn't written correctly to auto-close this issue. Glad I was able to contribute a fix to my own bug!
