### ISSUE TITLE
Wrong syntax highlighting in coffee for inline function without parameterlist

### ISSUE THREAD

**Issue by m-lautenbach** [atom/language-coffee-script#79]
Syntax Highlighting seems off here, as these expressions are equal.
I build atom directly from the repository.
Well a fork actually, created 4th of december.
Couldn't find this in issues for this filter: is:issue is:open syntax Highlighting coffee 

Example:

``` coffee
# correct, this has class inline function
obj.method () ->
# wrong, class is entity name function coffee, but this is a call
obj.method ->

# both lines are identical and valid,
#  the second one is actually more idomatic
```

<img width="1440" alt="bildschirmfoto 2015-12-08 um 20 24 56" src="https://cloud.githubusercontent.com/assets/2509770/11665879/e26cb118-9de9-11e5-9c3f-6b1154f636a7.png">

**Comment by lee-dohm** [comment]
There is a third version that is highlighted correctly and I would argue is also more idiomatic than the one that isn't highlighted correctly:

```coffee
obj.method() ->
```

**Comment by m-lautenbach** [comment]
Isn't this something else? You version call method method without arguments and calls the result with an empty function.
What I posted is calling the method method directly with an empty function.

**Comment by m-lautenbach** [comment]
Compare to Sublime, method calls look all the same
![bildschirmfoto 2015-12-10 um 15 01 36](https://cloud.githubusercontent.com/assets/2509770/11717181/f6def46a-9f4e-11e5-85de-3e7720171d05.png)
