### ISSUE TITLE
Not highlighting functions 2

### ISSUE THREAD

**Issue by pvorona** [atom/language-coffee-script#88]
**Sticky** is a function but it's not highlighted

![image](https://cloud.githubusercontent.com/assets/11915087/13359299/18f9a496-dcbc-11e5-9439-7f49442f7d63.png)

**Comment by lee-dohm** [comment]
What makes this different from #87? Given the title, it appears these are duplicates.

**Comment by pvorona** [comment]
@lee-dohm In this case there is no **do** keyword, and error occurs when using functions inside parameter list of other function with or without ```()``` and passing anonimous function to that function. Here is an example:
![image](https://cloud.githubusercontent.com/assets/11915087/13372521/32691fea-dd4f-11e5-8b2e-db7e503d81da.png)
**b** is highlighted appropriately
But if we pass anonimous function to **b**, than **b** is not highlighted
![image](https://cloud.githubusercontent.com/assets/11915087/13372529/626e3e96-dd4f-11e5-8e67-dfce2ff10736.png)
