### ISSUE TITLE
Function name sometimes not highlighted correctly

### ISSUE THREAD

**Issue by aleclarson** [atom/language-coffee-script#90]
If the `@` is removed, the function name is highlighted correctly.

``` coffee
obj.func @test
```

**Comment by aleclarson** [comment]
This also happens with a function name followed by the `=>` operator.

Example:
```coffee
obj.func => yes
```

**Comment by aleclarson** [comment]
This also happens with a function named followed by a parameter tuple.

```coffee
obj.func (param1) -> yes
```

**Comment by aleclarson** [comment]
This also happens with a function name followed by a parentheses.

```coffee
obj.func (a + b)
```

**Comment by 50Wliu** [comment]
I can no longer reproduce the first example but the others are still valid.
