### ISSUE TITLE
Escape sequences not highlighting in CSON multi-line string

### ISSUE THREAD

**Issue by Kroc** [atom/language-coffee-script#95]
The back-slashed characters in strings are not being highlighted in CSON multi-line strings; i.e.

```cson
somestring: '''
    the quick brown fox\n
    jumps over the lazy dog.
    '''
```

**Comment by lee-dohm** [comment]
This is because escape sequences are only escape sequences in double-quoted strings, not single-quoted. If you change the example to this, it works as you expect:

```coffee
somestring: """
    the quick brown fox\n
    jumps over the lazy dog.
    """
```
